# Generated by Django 4.1.3 on 2022-12-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_alter_user_password_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
